# -*- coding: utf-8 -*-
"""lin_reg_tensorflow

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15fHp9Y4CkzhiZtEoP27BGPNSoh9ldj-p
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

np.random.seed(0)
area = 2.5 * np.random.randn(100) + 25
price = 25 * area + np.random.randint(20, 50, size=len(area))

data = np.array([area, price])
data = pd.DataFrame(data = data.T, columns=['area', 'price'])

plt.scatter(data['area'], data['price'])
plt.show()

W = sum(price*(area - np.mean(area))) / sum((area - np.mean(area))**2)
b = np.mean(price) - W*np.mean(area)

print("Regression coefficients are", W, b)

y_pred = W * area + b

plt.plot(area, y_pred, color = 'red', label = "Predicted price")
plt.scatter(data['area'], data['price'], label = "training data")
plt.xlabel("Area")
plt.ylabel("Price")
plt.legend()